# Generated by Django 4.1.2 on 2025-05-23 11:14

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=17, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=180, verbose_name='密码')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='sweeping_user_groups', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='sweeping_user_permissions', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vin_code', models.CharField(max_length=17, unique=True, verbose_name='VIN码')),
                ('vehicle_number', models.CharField(max_length=20, verbose_name='车辆编号')),
                ('license_plate', models.CharField(max_length=10, verbose_name='车牌号')),
                ('manufacturer', models.CharField(max_length=50, verbose_name='生产厂家')),
                ('brand', models.CharField(max_length=50, verbose_name='品牌')),
                ('operation_date', models.DateField(verbose_name='投入运营日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '车辆',
                'verbose_name_plural': '车辆',
            },
        ),
        migrations.CreateModel(
            name='CalibrationParameter',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='参数名称')),
                ('code', models.CharField(max_length=30, verbose_name='参数代码')),
                ('value', models.CharField(max_length=100, verbose_name='参数值')),
                ('unit', models.CharField(blank=True, max_length=10, null=True, verbose_name='单位')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='参数描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('device_id', models.BigIntegerField(blank=True, null=True, verbose_name='关联设备ID')),
                ('device_type', models.CharField(choices=[('vehicle', '清扫车'), ('ship', '清洁船'), ('uav', '无人机')], max_length=20, verbose_name='设备类型')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人用户id')),
            ],
            options={
                'verbose_name': '校准参数',
                'verbose_name_plural': '校准参数',
                'db_table': 'sweeping_calibration_parameter',
            },
        ),
    ]
