# Generated by Django 4.1.2 on 2025-05-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sweeping", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedule",
            name="vehicle",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="user",
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=180, verbose_name="密码"),
        ),
        migrations.DeleteModel(
            name="Operation",
        ),
        migrations.DeleteModel(
            name="Schedule",
        ),
    ]
