# Generated by Django 4.1.2 on 2025-05-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweeping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibrationparameter',
            name='code',
            field=models.CharField(max_length=30, unique=True, verbose_name='参数代码'),
        ),
    ]
