# Generated by Django 4.1.2 on 2025-05-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sweeping", "0002_remove_schedule_vehicle_remove_vehicle_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Parameter",
            fields=[
                (
                    "param_UID",
                    models.BigAutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("param_Name", models.CharField(max_length=99, verbose_name="参数名")),
                (
                    "param_DataType",
                    models.CharField(
                        choices=[("0", "int"), ("1", "float"), ("2", "str")],
                        max_length=9,
                        verbose_name="数据类型",
                    ),
                ),
                (
                    "param_BODH",
                    models.CharField(
                        choices=[
                            ("b", "二进制"),
                            ("o", "八进制"),
                            ("d", "十进制"),
                            ("h", "十六进制"),
                        ],
                        max_length=9,
                        verbose_name="进制",
                    ),
                ),
                ("param_Value", models.CharField(max_length=99, verbose_name="参数值")),
                ("param_ValUnit", models.CharField(max_length=9, verbose_name="单位")),
                ("param_Origin", models.CharField(max_length=9, verbose_name="源")),
                (
                    "param_State",
                    models.CharField(max_length=9, verbose_name="参数状态"),
                ),
                (
                    "param_Record_Time",
                    models.DateTimeField(auto_now_add=True, verbose_name="记录时间"),
                ),
                (
                    "param_Users_Remark",
                    models.CharField(
                        blank=True, max_length=99, verbose_name="用户备注"
                    ),
                ),
            ],
            options={
                "verbose_name": "参数",
                "verbose_name_plural": "参数簇",
                "db_table": "parameters",
                "ordering": ["param_Name", "-param_Record_Time"],
            },
        ),
    ]
