# Generated by Django 4.1.2 on 2025-05-30 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sweeping', '0003_alter_calibrationparameter_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='参数名称')),
                ('code', models.CharField(max_length=30, verbose_name='参数代码')),
                ('value', models.CharField(max_length=100, verbose_name='参数值')),
                ('State', models.CharField(choices=[('0', 'int'), ('1', 'float'), ('2', 'str')], max_length=1, verbose_name='参数状态')),
                ('param_BODH', models.CharField(choices=[('b', '二进制'), ('o', '八进制'), ('d', '十进制'), ('h', '十六进制')], max_length=9, verbose_name='进制')),
                ('unit', models.CharField(blank=True, max_length=10, null=True, verbose_name='单位')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='参数描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('device_id', models.BigIntegerField(blank=True, null=True, verbose_name='关联设备ID')),
                ('device_type', models.CharField(choices=[('vehicle', '清扫车'), ('ship', '清洁船'), ('uav', '无人机')], max_length=20, verbose_name='设备类型')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人用户id')),
            ],
            options={
                'verbose_name': '校准参数',
                'verbose_name_plural': '校准参数',
                'db_table': 'sweeping_calibration_parameter',
            },
        ),
        migrations.DeleteModel(
            name='CalibrationParameter',
        ),
    ]
