# Generated by Django 4.1.2 on 2025-05-30 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("sweeping", "0003_parameter"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="parameter",
            options={
                "ordering": ["name", "-update_at"],
                "verbose_name": "参数",
                "verbose_name_plural": "参数簇",
            },
        ),
        migrations.RenameField(
            model_name="parameter",
            old_name="param_UID",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="parameter",
            old_name="param_Name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="parameter",
            old_name="param_ValUnit",
            new_name="unit",
        ),
        migrations.RenameField(
            model_name="parameter",
            old_name="param_Value",
            new_name="value",
        ),
        migrations.RemoveField(
            model_name="parameter",
            name="param_BODH",
        ),
        migrations.RemoveField(
            model_name="parameter",
            name="param_DataType",
        ),
        migrations.RemoveField(
            model_name="parameter",
            name="param_Origin",
        ),
        migrations.RemoveField(
            model_name="parameter",
            name="param_Record_Time",
        ),
        migrations.RemoveField(
            model_name="parameter",
            name="param_State",
        ),
        migrations.RemoveField(
            model_name="parameter",
            name="param_Users_Remark",
        ),
        migrations.AddField(
            model_name="parameter",
            name="code",
            field=models.CharField(
                choices=[("0", "bool"), ("1", "int"), ("2", "float"), ("3", "str")],
                default=1,
                max_length=1,
                verbose_name="数据类型",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parameter",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="创建时间",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parameter",
            name="description",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="参数描述"
            ),
        ),
        migrations.AddField(
            model_name="parameter",
            name="device_id",
            field=models.BigIntegerField(
                default=0, max_length=99, verbose_name="目标设备"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parameter",
            name="device_type",
            field=models.CharField(
                choices=[("vehicle", "清扫车"), ("ship", "清洁船"), ("uav", "无人机")],
                default=1,
                max_length=7,
                verbose_name="设备类型",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parameter",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="启用标志"),
        ),
        migrations.AddField(
            model_name="parameter",
            name="nst",
            field=models.CharField(
                choices=[
                    ("b", "二进制"),
                    ("o", "八进制"),
                    ("d", "十进制"),
                    ("h", "十六进制"),
                ],
                default=1,
                max_length=1,
                verbose_name="进制",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parameter",
            name="state",
            field=models.CharField(
                choices=[("0", "仅提交"), ("1", "已标定"), ("2", "出错")],
                default=0,
                max_length=1,
                verbose_name="标定状态",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parameter",
            name="update_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AddField(
            model_name="parameter",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="操作人",
            ),
        ),
        migrations.AlterModelTable(
            name="parameter",
            table="sweeping_parameters",
        ),
    ]
