# Generated by Django 4.1.2 on 2025-05-30 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sweeping', '0005_alter_parameter_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameter',
            name='user',
        ),
    ]
